"""init schema

Revision ID: 5454144b17bd
Revises: 
Create Date: 2026-05-26 10:33:53.219129

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5454144b17bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('banners',
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('link_to', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banners_position'), ['position'], unique=False)

    op.create_table('city_ips',
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('coupons',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('claimed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultural_elements',
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('style_hint', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cultural_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cultural_elements_city'), ['city'], unique=False)

    op.create_table('files',
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_owner_id'), ['owner_id'], unique=False)

    op.create_table('model_channels',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=256), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('model_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_channels_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_channels_is_active'), ['is_active'], unique=False)

    op.create_table('orders',
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('delivery_type', sa.String(length=16), nullable=False),
    sa.Column('amount_goods', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_shipping', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pay_method', sa.String(length=16), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['user_coupons.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('partners',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('profit_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bank_card', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_withdrew', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_username'), ['username'], unique=True)

    op.create_table('pattern_categories',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('push_messages',
    sa.Column('user_type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('link_to', sa.String(length=256), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_messages_user_id'), ['user_id'], unique=False)

    op.create_table('qr_codes',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('owner_type', sa.String(length=16), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_qr_codes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_type'), ['type'], unique=False)

    op.create_table('stores',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('management_fee_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('settle_mode', sa.String(length=16), nullable=False),
    sa.Column('bank_card', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promotion', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_username'), ['username'], unique=True)

    op.create_table('system_configs',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=True)

    op.create_table('topics',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('link_to', sa.String(length=256), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_coupons',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coupons_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coupons_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('openid_wx', sa.String(length=64), nullable=True),
    sa.Column('openid_dy', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_openid_dy'), ['openid_dy'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_openid_wx'), ['openid_wx'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('addresses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('ai_generations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.String(length=1024), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=True),
    sa.Column('source_image_url', sa.String(length=512), nullable=True),
    sa.Column('model_channel_id', sa.Integer(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_urls', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_channel_id'], ['model_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generations_user_id'), ['user_id'], unique=False)

    op.create_table('ai_preprocess_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('operations', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['output_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_preprocess_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_preprocess_logs_user_id'), ['user_id'], unique=False)

    op.create_table('city_ip_items',
    sa.Column('city_ip_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_ip_id'], ['city_ips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city_ip_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_ip_items_city_ip_id'), ['city_ip_id'], unique=False)

    op.create_table('city_ip_style_weights',
    sa.Column('city_ip_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_ip_id'], ['city_ips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city_ip_style_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_ip_style_weights_city_ip_id'), ['city_ip_id'], unique=False)

    op.create_table('devices',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ink_level', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_order_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_sn'), ['sn'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_store_id'), ['store_id'], unique=False)

    op.create_table('order_status_logs',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('operator_type', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_logs_order_id'), ['order_id'], unique=False)

    op.create_table('patterns',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('thumb_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pattern_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_category_id'), ['category_id'], unique=False)

    op.create_table('payout_records',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_records_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_records_partner_id'), ['partner_id'], unique=False)

    op.create_table('products',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('main_image_url', sa.String(length=512), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('available_colors', sa.JSON(), nullable=True),
    sa.Column('available_sizes', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)

    op.create_table('reconciliations',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_payout', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_mgmt_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('diff', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abnormal_count', sa.Integer(), nullable=False),
    sa.Column('abnormal_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliations_date'), ['date'], unique=True)

    op.create_table('settle_records',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('management_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settle_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settle_records_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settle_records_store_id'), ['store_id'], unique=False)

    op.create_table('store_staff',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_staff_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_staff_username'), ['username'], unique=True)

    op.create_table('user_prefs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pref_type', 'value', name='uq_user_pref')
    )
    with op.batch_alter_table('user_prefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_prefs_user_id'), ['user_id'], unique=False)

    op.create_table('withdrawals',
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_card', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('audit_remark', sa.String(length=256), nullable=True),
    sa.Column('audited_by', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audited_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawals_owner_id'), ['owner_id'], unique=False)

    op.create_table('device_status_logs',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('ink_level', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_status_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_status_logs_device_id'), ['device_id'], unique=False)

    op.create_table('product_skus',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_skus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_skus_product_id'), ['product_id'], unique=False)

    op.create_table('designs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('layers', sa.JSON(), nullable=True),
    sa.Column('preview_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_designs_user_id'), ['user_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_user_id'), ['user_id'], unique=False)

    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('design_id', sa.BigInteger(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('color_snapshot', sa.String(length=32), nullable=True),
    sa.Column('size_snapshot', sa.String(length=16), nullable=True),
    sa.Column('preview_url', sa.String(length=512), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_user_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_designs_user_id'))

    op.drop_table('designs')
    with op.batch_alter_table('product_skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_skus_product_id'))

    op.drop_table('product_skus')
    with op.batch_alter_table('device_status_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_status_logs_device_id'))

    op.drop_table('device_status_logs')
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_owner_id'))

    op.drop_table('withdrawals')
    with op.batch_alter_table('user_prefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prefs_user_id'))

    op.drop_table('user_prefs')
    with op.batch_alter_table('store_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_staff_username'))
        batch_op.drop_index(batch_op.f('ix_store_staff_store_id'))

    op.drop_table('store_staff')
    with op.batch_alter_table('settle_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settle_records_store_id'))
        batch_op.drop_index(batch_op.f('ix_settle_records_order_id'))

    op.drop_table('settle_records')
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliations_date'))

    op.drop_table('reconciliations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_records_partner_id'))
        batch_op.drop_index(batch_op.f('ix_payout_records_order_id'))

    op.drop_table('payout_records')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_category_id'))

    op.drop_table('patterns')
    with op.batch_alter_table('order_status_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_logs_order_id'))

    op.drop_table('order_status_logs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_store_id'))
        batch_op.drop_index(batch_op.f('ix_devices_sn'))

    op.drop_table('devices')
    with op.batch_alter_table('city_ip_style_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_ip_style_weights_city_ip_id'))

    op.drop_table('city_ip_style_weights')
    with op.batch_alter_table('city_ip_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_ip_items_city_ip_id'))

    op.drop_table('city_ip_items')
    with op.batch_alter_table('ai_preprocess_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_preprocess_logs_user_id'))

    op.drop_table('ai_preprocess_logs')
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generations_user_id'))

    op.drop_table('ai_generations')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))

    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_openid_wx'))
        batch_op.drop_index(batch_op.f('ix_users_openid_dy'))
        batch_op.drop_index(batch_op.f('ix_users_city'))

    op.drop_table('users')
    with op.batch_alter_table('user_coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_coupons_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_coupons_coupon_id'))

    op.drop_table('user_coupons')
    op.drop_table('topics')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))

    op.drop_table('system_configs')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_username'))
        batch_op.drop_index(batch_op.f('ix_stores_city'))

    op.drop_table('stores')
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_codes_type'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_qr_codes_code'))

    op.drop_table('qr_codes')
    with op.batch_alter_table('push_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_messages_user_id'))

    op.drop_table('push_messages')
    op.drop_table('product_categories')
    op.drop_table('pattern_categories')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_username'))
        batch_op.drop_index(batch_op.f('ix_partners_phone'))

    op.drop_table('partners')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_store_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_partner_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))

    op.drop_table('orders')
    with op.batch_alter_table('model_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_channels_is_active'))
        batch_op.drop_index(batch_op.f('ix_model_channels_enabled'))

    op.drop_table('model_channels')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_owner_id'))

    op.drop_table('files')
    with op.batch_alter_table('cultural_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cultural_elements_city'))

    op.drop_table('cultural_elements')
    op.drop_table('coupons')
    op.drop_table('city_ips')
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banners_position'))

    op.drop_table('banners')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
